# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastcflare',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/fastcflare',
                'lib_path': 'fastcflare'},
  'syms': { 'fastcflare.core': { 'fastcflare.core._cf_info': ('core.html#_cf_info', 'fastcflare/core.py'),
                                 'fastcflare.core._deets': ('core.html#_deets', 'fastcflare/core.py'),
                                 'fastcflare.core._mk_param': ('core.html#_mk_param', 'fastcflare/core.py'),
                                 'fastcflare.core._mk_sig': ('core.html#_mk_sig', 'fastcflare/core.py'),
                                 'fastcflare.core.build_cf_eps': ('core.html#build_cf_eps', 'fastcflare/core.py')}}}
