# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['build_cf_eps']

# %% ../nbs/00_core.ipynb #2b79e1ee
from fastcore.utils import *

import httpx
from inspect import Parameter,Signature
from jsonref import loads as jloads

# %% ../nbs/00_core.ipynb #33654c70
def _mk_param(name, **kwargs):
    kwargs.pop('description', None)
    name = name.replace('.', '_').replace('-', '_')
    if name == 'expand': kwargs['annotation'] = list
    return Parameter(name, kind=Parameter.POSITIONAL_OR_KEYWORD, **kwargs)

def _mk_sig(req_args, opt_args, anno_args):
    'req_args are args inside paths such as {account}, opt_args are query params, anno_args are payload params'
    params =  [_mk_param(k) for k in req_args]
    params += [_mk_param(**{'default': None} | p) for p in opt_args or anno_args]
    return Signature(params)

def _deets(k,v):
    'Extracts the type and default value from a schema'
    return {'name': k, 'description': v.get('description', ''),
        'annotation': _lu_type[v.get('type', 'NA')], 'default' : v.get('default', None)}

_lu_type = dict(zip(
    'NA string object array boolean number integer'.split(),
    map(PrettyString,'object str dict list bool int int'.split())
))

def _cf_info(desc):
    data = nested_idx(desc, *'requestBody content application/json schema properties'.split()) or {}
    data = [_deets(*o) for o in data.items()]
    params = desc.get('parameters', [])
    qparams = [dict(name=p['name'], description=p.get('description','')) for p in params if p.get('in')=='query']
    return dict(data=data, op_id=desc.get('operationId',''), qparams=qparams, summary=desc.get('summary',''),
                tags=desc.get('tags',[]))

# %% ../nbs/00_core.ipynb #624fd59f
def build_cf_eps():
    _pkg = Path(__file__).parent if '__file__' in globals() else Path('../fastcflare')
    spec = jloads((_pkg/'openapi.json').read_text())
    return [dict(path=p, verb=v, **_cf_info(desc))
            for p,vs in spec['paths'].items() for v,desc in vs.items() if v in _verbs]
