# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['CF_OPENAPI_URL', 'cf_names', 'cf_group_func', 'build_spec', 'CloudflareApi']

# %% ../nbs/00_core.ipynb #2b79e1ee
import json
from fastcore.utils import *
from fastcore.net import urlread
from fastspec.oapi import SpecParser, OpenAPIClient
from fastcore.apisurface import snake
from collections import defaultdict

# %% ../nbs/00_core.ipynb #73d561f3
def _canon(verb, path): return verb.lower(), tuple(snake(s.strip('{}')) if s.startswith('{') else snake(s) for s in path.strip('/').split('/'))

def _op_parts(path):
    "Snaked non-param segments, collection flag (path ends on a non-param segment), and param names"
    segs = path.strip('/').split('/')
    return [snake(s) for s in segs if not s.startswith('{')], not segs[-1].startswith('{'), [s.strip('{}') for s in segs if s.startswith('{')]

# %% ../nbs/00_core.ipynb #fd2d07d1
def cf_names(spec):
    "Map each op's canonical (verb, snaked-segments) key to (group_segments, op_name), collision-free across the surface"
    ops = {}
    for p, item in spec['paths'].items():
        for v in item:
            if v in ('get','post','put','patch','delete','head','options'): ops.setdefault(_canon(v,p), p)
    gets = defaultdict(set)
    for (v,_),p in ops.items():
        g, coll, _ = _op_parts(p)
        if v=='get': gets[tuple(g)].add(coll)
    res = {}
    for k,p in ops.items():
        v = k[0]
        g, coll, ps = _op_parts(p)
        nm = 'list' if v=='get' and coll and len(gets[tuple(g)])==2 else v
        res[k] = [tuple(g), nm, ps]
    sibs = defaultdict(list)
    for k,(g,n,ps) in res.items(): sibs[(g,n)].append(k)
    for ks in sibs.values():
        if len(ks)==1: continue
        common = set.intersection(*(set(res[k][2]) for k in ks))
        for k in ks:
            extra = [q for q in res[k][2] if q not in common]
            if extra: res[k][1] += '_by_'+'_'.join(extra)
    opnms, kids = defaultdict(set), defaultdict(set)
    for g,n,_ in res.values():
        opnms[g].add(n)
        for i in range(1,len(g)): kids[g[:i]].add(g[i])
    for g,seg in [(g,s) for g in opnms for s in kids[g]&opnms[g]]:
        for k,(og,n,ps) in res.items():
            if og==g+(seg,): res[k] = [g, f'{seg}_{n}', ps]
    return {k:(list(g),n) for k,(g,n,ps) in res.items()}

# %% ../nbs/00_core.ipynb #30441f94
def cf_group_func(names):
    "A fastspec `group_func` looking up precomputed `names` by canonical verb+path"
    def f(op_id, path, verb='', path_tags=None, op_tags=None): return names[_canon(verb, path)]
    return f

# %% ../nbs/00_core.ipynb #372333d0
CF_OPENAPI_URL = 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.json'

def build_spec(nm='fastcflare/cf_spec.py', url=CF_OPENAPI_URL):
    "Regenerate the compact spec module `cf_spec.py` from Cloudflare's OpenAPI schema."
    schema = dict2obj(json.loads(urlread(url)))
    SpecParser.from_openapi(schema, cf_group_func(cf_names(schema))).save(nm)

def _cf_spec():
    from fastcflare.cf_spec import spec
    return SpecParser.from_dict(spec)

# %% ../nbs/00_core.ipynb #dd30d894
class CloudflareApi:
    "Cloudflare API client supporting both user and account tokens"
    def __init__(self, token=None, account_id=None, email=None, api_key=None):
        if not token and not api_key: token = os.getenv('CF_API_TOKEN')
        if api_key and not email: email = os.getenv('CF_API_EMAIL')
        store_attr()
        if api_key: hdrs = {'X-Auth-Email': email, 'X-Auth-Key': api_key, 'Content-Type': 'application/json'}
        else: hdrs = {'Authorization': f'Bearer {token}', 'Content-Type': 'application/json'}
        self.cli = OpenAPIClient(_cf_spec(), headers=hdrs, timeout=60.0)
        self.groups = self.cli.groups

    async def verify(self):
        if self.account_id: return await self.accounts.tokens.verify.get(account_id=self.account_id)
        return await self.user.tokens.verify.get()

    def __dir__(self): return super().__dir__() + list(self.groups)
    def _repr_markdown_(self): return "\n".join(f"- {o}" for o in sorted(self.groups))
    def __getattr__(self, k): return self.groups[k] if 'groups' in vars(self) and k in self.groups else stop(AttributeError(k))

# %% ../nbs/00_core.ipynb #de443569
@patch
async def create_token(self:CloudflareApi, doms, perm_names, name, grp='account.zone.'):
    "Create a scoped Cloudflare API token for given domains and permission names"
    pref = 'com.cloudflare.api.'+grp
    pgs = (await self.user.tokens.permission_groups.get()).result
    perms = [dict(id=p.id) for p in pgs if p.name in perm_names]
    zids = {f'{pref}{(await self.zones.list(name=d)).result[0].id}':'*' for d in doms}
    return await self.user.tokens.post(name=name, policies=[dict(effect='allow', resources=zids, permission_groups=perms)])
